---
version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    environment:
      - VUE_APP_BACKEND_SCHEME=${TONIE_AUDIO_MATCH_BACKEND_SCHEME}
      - VUE_APP_BACKEND_HOST=${TONIE_AUDIO_MATCH_BACKEND_HOST}
      - VUE_APP_BACKEND_PORT=${TONIE_AUDIO_MATCH_BACKEND_PORT}
    networks:
      - toniebox
    ports:
      - ${TONIE_AUDIO_MATCH_FRONTEND_PORT}:8080
    volumes:
      - ./albumart/:/frontend/public/assets/covers

  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
    environment:
      - TONIE_AUDIO_MATCH_MEDIA_PATH
      - TONIE_AUDIO_MATCH_USER
      - TONIE_AUDIO_MATCH_PASS
    networks:
      - toniebox
    ports:
      - ${TONIE_AUDIO_MATCH_BACKEND_PORT}:5000
    volumes:
      - ./albumart/:/backend/assets/covers
      - ${TONIE_AUDIO_MATCH_MEDIA_PATH}:/backend/assets/audiobooks

networks:
  toniebox:
