---
version: '3'
services:
  frontend:
    image: node:14.7-stretch
    environment:
      - VUE_APP_BACKEND_SCHEME=${TONIE_AUDIO_MATCH_BACKEND_SCHEME}
      - VUE_APP_BACKEND_HOST=${TONIE_AUDIO_MATCH_BACKEND_HOST}
      - VUE_APP_BACKEND_PORT=${TONIE_AUDIO_MATCH_BACKEND_PORT}
    command: >
      bash -c "cd /frontend &&
      npm install &&
      npm run serve"
    networks:
      - toniebox
    ports:
      - ${TONIE_AUDIO_MATCH_FRONTEND_PORT}:8080
    volumes:
      - ./client/:/frontend
      - ./albumart/:/frontend/public/assets/covers

  backend:
    image: python:3.8-buster
    environment:
      - TONIE_AUDIO_MATCH_MEDIA_PATH
      - TONIE_AUDIO_MATCH_USER
      - TONIE_AUDIO_MATCH_PASS
      - TONIE_AUDIO_MATCH_REDIS_URI
    command: >
      bash -c "cd /backend &&
      pip install -r requirements.txt &&
      python app.py"
    networks:
      - toniebox
    ports:
      - ${TONIE_AUDIO_MATCH_BACKEND_PORT}:5000
    volumes:
      - ./server/:/backend
      - ./albumart/:/backend/assets/covers
      - ${TONIE_AUDIO_MATCH_MEDIA_PATH}:/backend/assets/audiobooks
    depends_on:
      - redis

  backend-worker:
    image: python:3.8-buster
    environment:
      - TONIE_AUDIO_MATCH_USER
      - TONIE_AUDIO_MATCH_PASS
      - TONIE_AUDIO_MATCH_REDIS_URI
    command: >
      bash -c "cd /backend &&
      pip install -r requirements.txt &&
      rq worker --url ${TONIE_AUDIO_MATCH_REDIS_URI} --with-scheduler --logging_level DEBUG"
    networks:
      - toniebox
    volumes:
      - ./server/:/backend
      - ${TONIE_AUDIO_MATCH_MEDIA_PATH}:/backend/assets/audiobooks
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    networks:
      - toniebox

networks:
  toniebox: